blog/urls.py
from django.urls import path
from . import views

urlpatterns = [
    path('', views.home, name='blog-home'),
    path('nova/', views.nova, name='blog-nova'),
    path('editar/<int:pk>/', views.editar, name='blog-editar'),
    path('deletar/<int:pk>/', views.deletar, name='blog-deletar'),
]

config/urls.py
from django.contrib import admin
from django.urls import path , include
urlpatterns = [
    path('admin/', admin.site.urls),
    path('blog/', include('blog.urls')),
    path('', include('portofolio.urls')),
    path('', include('users.urls')),
]

portofolio/urls.py
#Urls.py
from django.urls import path
from . import views
from django.conf import settings
from django.conf.urls.static import static

app_name = 'portofolio'

urlpatterns = [

    path('backend/', views.home, name='home'),
    
    path('backend/pessoas/', views.pessoas_form, name='pessoas_insert'), # get and post req. for insert operation
    path('backend/pessoas/list/', views.pessoas_list, name='pessoas_list'), # get req. to retrieve and display all records
    path('backend/pessoas/update/<int:id>', views.pessoas_form, name='pessoa_update'), # get and post req. for update operation
    path('backend/pessoas/delete/<int:id>', views.pessoas_delete, name='pessoa_delete'), # get req. to delete operation

    path('backend/professores/', views.professores_form, name='professores_insert'), # get and post req. for insert operation
    path('backend/professores/list/', views.professores_list, name='professores_list'), # get req. to retrieve and display all records
    path('backend/professores/update/<int:id>', views.professores_form, name='professor_update'), # get and post req. for update operation
    path('backend/professores/delete/<int:id>', views.professores_delete, name='professor_delete'), # get req. to delete operation

    path('backend/escolas/', views.escolas_form, name='escolas_insert'), # get and post req. for insert operation
    path('backend/escolas/list/', views.escolas_list, name='escolas_list'), # get req. to retrieve and display all records
    path('backend/escolas/update/<int:id>', views.escolas_form, name='escola_update'), # get and post req. for update operation
    path('backend/escolas/delete/<int:id>', views.escolas_delete, name='escola_delete'), # get req. to delete operation

    path('backend/universidades/', views.universidades_form, name='universidades_insert'), # get and post req. for insert operation
    path('backend/universidades/list/', views.universidades_list, name='universidades_list'), # get req. to retrieve and display all records
    path('backend/universidades/update/<int:id>', views.universidades_form, name='universidade_update'), # get and post req. for update operation
    path('backend/universidades/delete/<int:id>', views.universidades_delete, name='universidade_delete'), # get req. to delete operation

    path('backend/cursos/', views.cursos_form, name='cursos_insert'), # get and post req. for insert operation
    path('backend/cursos/list/', views.cursos_list, name='cursos_list'), # get req. to retrieve and display all records
    path('backend/cursos/update/<int:id>', views.cursos_form, name='curso_update'), # get and post req. for update operation
    path('backend/cursos/delete/<int:id>', views.cursos_delete, name='curso_delete'), # get req. to delete operation

    path('backend/cadeiras/', views.cadeiras_form, name='cadeiras_insert'), # get and post req. for insert operation
    path('backend/cadeiras/list/', views.cadeiras_list, name='cadeiras_list'), # get req. to retrieve and display all records
    path('backend/cadeiras/update/<int:id>', views.cadeiras_form, name='cadeira_update'), # get and post req. for update operation
    path('backend/cadeiras/delete/<int:id>', views.cadeiras_delete, name='cadeira_delete'), # get req. to delete operation

    path('backend/projetos/', views.projetos_form, name='projetos_insert'), # get and post req. for insert operation
    path('backend/projetos/list/', views.projetos_list, name='projetos_list'), # get req. to retrieve and display all records
    path('backend/projetos/update/<int:id>', views.projetos_form, name='projeto_update'), # get and post req. for update operation
    path('backend/projetos/delete/<int:id>', views.projetos_delete, name='projeto_delete'), # get req. to delete operation

    path('backend/linguagens/', views.linguagens_form, name='linguagens_insert'), # get and post req. for insert operation
    path('backend/linguagens/list/', views.linguagens_list, name='linguagens_list'), # get req. to retrieve and display all records
    path('backend/linguagens/update/<int:id>', views.linguagens_form, name='linguagem_update'), # get and post req. for update operation
    path('backend/linguagens/delete/<int:id>', views.linguagens_delete, name='linguagem_delete'), # get req. to delete operation

    path('backend/experiencias-profissionais/', views.experiencias_profissionais_form, name='experiencias_profissionais_insert'), # get and post req. for insert operation
    path('backend/experiencias-profissionais/list/', views.experiencias_profissionais_list, name='experiencias_profissionais_list'), # get req. to retrieve and display all records
    path('backend/experiencias-profissionais/update/<int:id>', views.experiencias_profissionais_form, name='experiencia_profissional_update'), # get and post req. for update operation
    path('backend/experiencias-profissionais/delete/<int:id>', views.experiencias_profissionais_delete, name='experiencia_profissional_delete'), # get req. to delete operation

    path('backend/aptidoes/', views.aptidoes_form, name='aptidoes_insert'), # get and post req. for insert operation
    path('backend/aptidoes/list/', views.aptidoes_list, name='aptidoes_list'), # get req. to retrieve and display all records
    path('backend/aptidoes/update/<int:id>', views.aptidoes_form, name='aptidao_update'), # get and post req. for update operation
    path('backend/aptidoes/delete/<int:id>', views.aptidoes_delete, name='aptidao_delete'), # get req. to delete operation

    path('backend/interesses/', views.interesses_form, name='interesses_insert'), # get and post req. for insert operation
    path('backend/interesses/list/', views.interesses_list, name='interesses_list'), # get req. to retrieve and display all records
    path('backend/interesses/update/<int:id>', views.interesses_form, name='interesse_update'), # get and post req. for update operation
    path('backend/interesses/delete/<int:id>', views.interesses_delete, name='interesse_delete'), # get req. to delete operation

    path('backend/tecnologias/', views.tecnologias_form, name='tecnologias_insert'), # get and post req. for insert operation
    path('backend/tecnologias/list/', views.tecnologias_list, name='tecnologias_list'), # get req. to retrieve and display all records
    path('backend/tecnologias/update/<int:id>', views.tecnologias_form, name='tecnologia_update'), # get and post req. for update operation
    path('backend/tecnologias/delete/<int:id>', views.tecnologias_delete, name='tecnologia_delete'), # get req. to delete operation

    path('backend/tipo-tecnologias/', views.tipo_tecnologias_form, name='tipo_tecnologias_insert'), # get and post req. for insert operation
    path('backend/tipo-tecnologias/list/', views.tipo_tecnologias_list, name='tipo_tecnologias_list'), # get req. to retrieve and display all records
    path('backend/tipo-tecnologias/update/<int:id>', views.tipo_tecnologias_form, name='tipo_tecnologia_update'), # get and post req. for update operation
    path('backend/tipo-tecnologias/delete/<int:id>', views.tipo_tecnologias_delete, name='tipo_tecnologia_delete'), # get req. to delete operation

    path('backend/tipo-aptidoes/', views.tipo_aptidoes_form, name='tipo_aptidoes_insert'), # get and post req. for insert operation
    path('backend/tipo-aptidoes/list/', views.tipo_aptidoes_list, name='tipo_aptidoes_list'), # get req. to retrieve and display all records
    path('backend/tipo-aptidoes/update/<int:id>', views.tipo_aptidoes_form, name='tipo_aptidao_update'), # get and post req. for update operation
    path('backend/tipo-aptidoes/delete/<int:id>', views.tipo_aptidoes_delete, name='tipo_aptidao_delete'), # get req. to delete operation

    path('backend/tipo-projetos/', views.tipo_projetos_form, name='tipo_projetos_insert'), # get and post req. for insert operation
    path('backend/tipo-projetos/list/', views.tipo_projetos_list, name='tipo_projetos_list'), # get req. to retrieve and display all records
    path('backend/tipo-projetos/update/<int:id>', views.tipo_projetos_form, name='tipo_projeto_update'), # get and post req. for update operation
    path('backend/tipo-projetos/delete/<int:id>', views.tipo_projetos_delete, name='tipo_projeto_delete'), # get req. to delete operation

    # Frontend urls
    path('download/', views.download_file, name='download_file'),
    path('', views.index, name='index'),
    path('studies/', views.studies, name='studies'),
    path('discipline/<int:id>', views.discipline, name='discipline'),
    path('skills/', views.skills, name='skills'),
    path('interests/', views.interests, name='interests'),
    path('project<int:id>', views.project, name='project'),
    path('web/', views.web, name='web'),
    path('page_details/', views.page_details, name='page_details'),

] + static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

portofolio/forms.py
from django import forms
from .models import Pessoa
from .models import Professor
from .models import Escola
from .models import Universidade
from .models import Curso
from .models import Cadeira
from .models import Projeto
from .models import Linguagem
from .models import ExperienciaProfissional
from .models import Aptidao
from .models import Tecnologia
from .models import TipoTecnologia
from .models import TipoAptidao
from .models import TipoProjeto
from .models import Interesse

class PessoaForm(forms.ModelForm):

    class Meta:
        model = Pessoa
        fields ='__all__'
    

class ProfessorForm(forms.ModelForm):

    class Meta:
        model = Professor
        fields ='__all__'

    # Select field tem de ser Escolhe a Universidade
    def __init__(self, *args, **kwargs):
        super(ProfessorForm, self).__init__(*args, **kwargs)
        self.fields['universidade'].empty_label = "Escolhe a Universidade"

class EscolaForm(forms.ModelForm):

    class Meta:
        model = Escola
        fields ='__all__'
        widgets = {
            'inicio': forms.DateInput(attrs={'type': 'date'}),
            'fim': forms.DateInput(attrs={'type': 'date'}),
        }

    # Select field tem de ser Escolhe a Pessoa
    def __init__(self, *args, **kwargs):
        super(EscolaForm, self).__init__(*args, **kwargs)
        self.fields['pessoa'].empty_label = "Escolhe a Pessoa"

class UniversidadeForm(forms.ModelForm):
    
    class Meta:
        model = Universidade
        fields ='__all__'
        widgets = {
            'inicio': forms.DateInput(attrs={'type': 'date'}),
            'fim': forms.DateInput(attrs={'type': 'date'}),
        }

    # Select field tem de ser Escolhe a Pessoa
    def __init__(self, *args, **kwargs):
        super(UniversidadeForm, self).__init__(*args, **kwargs)
        self.fields['pessoa'].empty_label = "Escolhe a Pessoa"

class CursoForm(forms.ModelForm):
        
    class Meta:
        model = Curso
        fields ='__all__'
        widgets = {
            'inicio': forms.DateInput(attrs={'type': 'date'}),
            'fim': forms.DateInput(attrs={'type': 'date'}),
        }

    # Select field tem de ser Escolhe a Pessoa
    def __init__(self, *args, **kwargs):
        super(CursoForm, self).__init__(*args, **kwargs)
        self.fields['professor'].empty_label = "Escolhe o Professor"
        self.fields['universidade'].empty_label = "Escolhe a Universidade"

class InteresseForm(forms.ModelForm):

    class Meta:
        model = Interesse
        fields ='__all__'

class CadeiraForm(forms.ModelForm):
            
    class Meta:
        model = Cadeira
        fields ='__all__'
        widgets = {
            'inicio': forms.DateInput(attrs={'type': 'date'}),
            'fim': forms.DateInput(attrs={'type': 'date'}),
        }

    # Select field tem de ser Escolhe a Pessoa
    def __init__(self, *args, **kwargs):
        super(CadeiraForm, self).__init__(*args, **kwargs)
        self.fields['curso'].empty_label = "Escolhe o Curso"

class ProjetoForm(forms.ModelForm):
    tecnologias = forms.ModelMultipleChoiceField(queryset=Tecnologia.objects.all(), widget=forms.CheckboxSelectMultiple)
    linguagens = forms.ModelMultipleChoiceField(queryset=Linguagem.objects.all(), widget=forms.CheckboxSelectMultiple)

    class Meta:
        model = Projeto
        fields ='__all__'

        
    # Select field tem de ser Escolhe a Pessoa
    def __init__(self, *args, **kwargs):
        super(ProjetoForm, self).__init__(*args, **kwargs)
        self.fields['pessoas'].empty_label = "Escolhe a Pessoas"
        self.fields['tipo'].empty_label = "Escolhe o Tipo"
        self.fields['tecnologias'].empty_label = None
        self.fields['cadeira'].empty_label = "Escolhe a Cadeira"
    
    # If the field is not required, it will not be validated on the server
    def clean_cadeira(self):
        # cadeira is not required
        if not self.cleaned_data['cadeira']:
            return None
        return self.cleaned_data['cadeira']


class LinguagemForm(forms.ModelForm):
                    
    class Meta:
        model = Linguagem
        fields ='__all__'
        
class ExperienciaProfissionalForm(forms.ModelForm):

    class Meta:
        model = ExperienciaProfissional
        fields ='__all__'
        widgets = {
            'inicio': forms.DateInput(attrs={'type': 'date'}),
            'fim': forms.DateInput(attrs={'type': 'date'}),
        }

    # Select field tem de ser Escolhe a Pessoa
    def __init__(self, *args, **kwargs):
        super(ExperienciaProfissionalForm, self).__init__(*args, **kwargs)
        self.fields['pessoa'].empty_label = "Escolhe a Pessoa"
                            
class AptidaoForm(forms.ModelForm):
                            
    class Meta:
        model = Aptidao
        fields ='__all__'

    # Select field tem de ser Escolhe a Pessoa
    def __init__(self, *args, **kwargs):
        super(AptidaoForm, self).__init__(*args, **kwargs)
        self.fields['pessoa'].empty_label = "Escolhe a Pessoa"
        self.fields['tipo'].empty_label = "Escolhe o Tipo"

class TecnologiaForm(forms.ModelForm):
        
    class Meta:
        model = Tecnologia
        fields ='__all__'

    # Select field tem de ser Escolhe a Pessoa
    def __init__(self, *args, **kwargs):
        super(TecnologiaForm, self).__init__(*args, **kwargs)
        self.fields['pessoa'].empty_label = "Escolhe a Pessoa"
        self.fields['tipo'].empty_label = "Escolhe o Tipo de Tecnologia"

class TipoTecnologiaForm(forms.ModelForm):
        
    class Meta:
        model = TipoTecnologia
        fields ='__all__'

class TipoAptidaoForm(forms.ModelForm):
            
    class Meta:
        model = TipoAptidao
        fields ='__all__'

class TipoProjetoForm(forms.ModelForm):
                
    class Meta:
        model = TipoProjeto
        fields ='__all__'

portofolio/templates/portofolio/educacao/cursos/curso_form.html
{%extends 'portofolio/base.html' %}
{%load crispy_forms_tags%}
{%block content%}
<div class="container">
    <div class="col-md-10 offset-md-1 mt-5">
        <div class="limiter-form jumbotron">
            <div class="container-flex">
                <a href="{%url 'portofolio:cursos_list'%}" class="btn btn-primary btn-sm">
                    <i class="fas fa-arrow-left"></i>
                        Voltar
                </a>
            </div>
            <h1 class="display-4">Registar Curso</h1>
            <p class="lead">Aqui irás conseguir adicionar cursos no Backend.</p>
            <hr class="my-4">
            <form action="" method="post" autocomplete="off">
                {% csrf_token %}
                <div class="row">
                    <div class="col-md-4">
                        {{form.nome|as_crispy_field}}
                    </div>
                    <div class="col-md-4">
                        {{form.ectsTotal|as_crispy_field}}
                    </div>
                    <div class="col-md-4">
                        {{form.professor|as_crispy_field}}
                    </div>
                </div>
                <div class="row">
                    <div class="col-md-6">
                        {{form.inicio|as_crispy_field}}
                    </div>
                    <div class="col-md-6">
                        {{form.fim|as_crispy_field}}
                    </div>
                </div>
                {{ form.universidade|as_crispy_field }}
                <button class="register-custom btn btn-sucess btn-lg" type="submit">
                    <i class="fas fa-user-plus"></i>
                        Registar
                </button>
            </form>
        </div>
    </div>
</div>
{%endblock%}

portofolio/templates/portofolio/educacao/cursos/curso_list.html
{%extends 'portofolio/base.html' %}
{%load crispy_forms_tags%}
{%block content%}
<div class="container">
    <div class="col-md-10 offset-md-1 mt-5">
        <div class="limiter-form jumbotron">
            <a href="{%url 'portofolio:cursos_insert'%}" class="btn btn-primary btn-sm">
                <i class="fas fa-user-plus"></i>
                Adicionar
            </a>
            <h1 class="display-4">Lista de Cursos</h1>
            <p class="lead">Aqui irás conseguir ver as cursos no Backend.</p>
            <hr class="my-4">
            <table class="table table-borderless">
                <thead class="border-bottom font-weight-bold">
                    <tr>
                        <td>Nome</td>
                        <td>Ects</td>
                        <td>Professor</td>
                        <td>Início</td>
                        <td>Fim</td>
                        <td>Opções</td>
                    </tr>
                    <tbody>
                        {%for curso in cursos_list%}
                        <tr>
                            <td>{{curso.nome}}</td>
                            <td>{{curso.ectsTotal}}</td>
                            <td>{{ curso.professor }}</td>
                            <td>{{ curso.inicio }}</td>
                            <td>{{ curso.fim }}</td>
                            <td>
                                <a href="{%url 'portofolio:curso_update' curso.id%}" class="btn btn-warning btn-sm">
                                    <i class="fas fa-user-edit"></i>
                                </a>
                                <form action="{%url 'portofolio:curso_delete' curso.id%}" method="post" class="d-inline">
                                    {%csrf_token%}
                                    <button type="submit" class="btn btn-danger btn-sm">
                                        <i class="fas fa-user-times"></i>
                                    </button>
                                </form>
                            </td>
                        </tr>
                        {% endfor %}
                    </tbody>
                </thead>
            </table>
        </div>
    </div>
</div>
{%endblock%}